# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0004_auto_20180930_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone_Number', models.CharField(blank=True, max_length=10)),
                ('Email', models.EmailField(max_length=254)),
                ('Subject', models.CharField(max_length=100)),
                ('Message', models.TextField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
