# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 08:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0005_auto_20180930_1417'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contct',
            new_name='Contact',
        ),
    ]
