# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-20 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('construction', '0006_auto_20180930_1417'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Phone_Number', models.CharField(blank=True, max_length=10)),
                ('Email', models.EmailField(blank=True, max_length=254)),
                ('Address', models.TextField(max_length=500)),
                ('Profession', models.CharField(choices=[('Welder', 'Freshman'), ('Helper', 'Helper'), ('Sweeper', 'Sweeper'), ('Maid', 'Maid')], max_length=50)),
            ],
        ),
    ]
